const musicsSampledIn = [
  {
    song: "Edwin Birdsong - Cola Bottle Baby",
    title: "Cola Bottle Baby",
    genre: "Soul / Funk / Disco",
    url: "https://www.youtube.com/embed/fiD39jo5Yo4",
    sample: "sample appears at 0:00 and 4:51",
    hasBeenPlayed: false,
    sampleIn: "Harder, Better, Faster, Stronger",
  },
  {
    song: "Golden Sounds - Zamina Mina (Zangalewa)",
    title: "Zamina Mina (Zangalewa)",
    genre: "world",
    url: "https://www.youtube.com/embed/EpHQAw6eCOY",
    sample: "sampole appears at 0:10 and 7:30",
    hasBeenPlayed: false,
    sampleIn: "Waka Waka (This Time for Africa)",
  },
  {
    song: "Charles Aznavour - Parce Que Tu Crois",
    title: "Parce Que Tu Crois",
    genre: "Rock / Pop",
    url: "https://www.youtube.com/embed/28nMw4zmdKE?",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "What's the difference",
  },
  {
    song: "Chaka Khan - Fate",
    title: "Fate",
    genre: "Soul / Funk / Disco",
    url: "https://www.youtube.com/embed/S0NbcNc3HOk?",
    sample: "sample appears at 0:03",
    hasBeenPlayed: false,
    sampleIn: "Music Sounds Better With You",
  },
  {
    song: "The Clash - Straight to Hell",
    title: "Straight to Hell",
    genre: "Rock / Pop",
    url: "https://www.youtube.com/embed/t7SvtikTkrM",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "Paper Planes",
  },
  {
    song: "Patrice Rushen - Forget Me Nots",
    title: "Forget Me Nots",
    genre: "Soul / Funk / Disco",
    url: "https://www.youtube.com/embed/jtMHsNhQBvI?",
    sample: "sample appears at 0:04",
    hasBeenPlayed: false,
    sampleIn: "Men in Black",
  },
];
