const musicsSampleOf = [
  {
    song: "Daft Punk - Harder, Better, Faster, Stronger",
    title: "Harder, Better, Faster, Stronger",
    genre: "Electronic / Dance",
    url: "https://www.youtube.com/embed/gAjR4_CbPpQ",
    sample: "sample appears at 0:05 and 0:20 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Shakira - Waka Waka (This Time for Africa)",
    title: "Waka Waka (This Time for Africa)",
    genre: "Rock / Pop",
    url: "https://www.youtube.com/embed/pRpeEdMmmQ0",
    sample: "sample appears at 0:59 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Dr Dre feat Eminem and Xzibit - What's the difference",
    title: "What's the difference",
    genre: "Hip-Hop / Rap / R&B",
    url: "https://www.youtube.com/embed/PANEcjhSfv4",
    sample: "sample appears at 0:00 ",
    hasBeenPlayed: false,
  },
  {
    song: "Stardust - Music Sounds Better With You",
    title: "Music Sounds Better With You",
    genre: "Electronic / Dance",
    url: "https://www.youtube.com/embed/FQlAEiCb8m0",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "M.I.A. - Paper Planes",
    title: "Paper Planes",
    genre: "Hip-Hop / Rap / R&B",
    url: "https://www.youtube.com/embed/ewRjZoRtu0Y",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Will Smith feat Coko - Men in Black",
    title: "Men in Black",
    genre: "Hip-Hop / Rap / R&B",
    url: "https://www.youtube.com/embed/fiBLgEx6svA",
    sample: "sample appears at 0:13 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "The Verve - Bitter Sweet Symphony",
    title: "Bitter Sweet Symphony",
    url: "https://www.youtube.com/embed/1lyu1KKwC74",
    sample: "sample appears at 0:03 and 0:25 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Shaggy - It Wasn't me",
    title: "It Wasn't me",
    url: "https://www.youtube.com/embed/sTMgX1PDGAE",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Beyonce - Crazy in Love",
    title: "Crazy in Love",
    url: "https://www.youtube.com/embed/ViwtNLUqkMY",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Michael Jackson - Beat It ",
    title: "Beat It",
    url: "https://www.youtube.com/embed/oRdxUFDoQe0",
    sample: "Sample appears at 0:21",
    hasBeenPlayed: false,
  },
  {
    song: "Britney Spears - Toxic",
    title: "Toxic",
    url: "https://www.youtube.com/embed/LOZuxwVk7TU",
    sample: "sample appears at 0:00 and 0:01",
    hasBeenPlayed: false,
  },
  {
    song: "Eminem, Dr Dre and 50 Cent - Crack a Bottle",
    title: "Crack a Bottle",
    url: "https://www.youtube.com/embed/HiVZbFhVeck",
    sample: "sample appears at 0:06 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Dr Dre feat Snoop Dogg, Nate Dogg and Kurupt - The Next Episode",
    title: "The Next Episode",
    url: "https://www.youtube.com/embed/QZXc39hT8t4",
    sample: "sample appears at 0:00, 0:05 abd 0:10 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Eminem - My Name Is",
    title: "My Name Is",
    url: "https://www.youtube.com/embed/LDj8kkVwisY",
    sample: "sample appears at 0:09 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "The Notorious B.I.G. feat Total - Juicy",
    title: "Juicy",
    url: "https://www.youtube.com/embed/_JZom_gVfuw",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Eric Prydz - Call on Me",
    title: "Call on Me",
    url: "https://www.youtube.com/embed/f-RJE6e5kSY",
    sample: "sample appears at 0:13 and 0:33 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Ice Cube - It Was a Good Day",
    title: "It Was a Good Day",
    url: "https://www.youtube.com/embed/h4UqMyldS7Q?start=9",
    sample: "sample appears at 0:10 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Modjo - Lady (Hear Me Tonight)",
    title: "Lady (Hear Me Tonight)",
    url: "https://www.youtube.com/embed/mMfxI3r_LyA",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Madonna - Hung Up",
    title: "Hung Up",
    url: "https://www.youtube.com/embed/EDwb9jOVRtU?start=30",
    sample: "sample appears at 0:32 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Drake - Hotline Bling",
    title: "Hotline Bling",
    url: "https://www.youtube.com/embed/uxpDa-c-4Mc",
    sample: "sample appears at 0:20 and 0:34 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Gotye feat Kimbra - Somebody That I used to Know",
    title: "Somebody That I used to Know",
    url: "https://www.youtube.com/embed/8UVNT4wvIGY",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Shakira feat Wyclef Jean - Hips Don't Lie",
    title: "Hips Don't Lie",
    url: "https://www.youtube.com/embed/DUT5rEU6pqM",
    sample: "sample appears at 0:00 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Fatboy Slim - Right Here, Right Now",
    title: "Right Here, Right Now",
    url: "https://www.youtube.com/embed/ub747pprmJ8",
    sample: "sample appears at 0:04 and 0:50",
    hasBeenPlayed: false,
  },
  {
    song: "Christophe Tyng - Futurama Theme",
    title: "Futurama Theme",
    url: "https://www.youtube.com/embed/jOqhtxRXVbU",
    sample: "sample appears at 0:05 (and throughout)",
    hasBeenPlayed: false,
  },
  {
    song: "Daft Punk - Digital Love",
    title: "Digital Love",
    url: "https://www.youtube.com/embed/FxzBvqY5PP0",
    sample: "sample appears at 0:00 and 1:51 tand throughout)",
    hasBeenPlayed: false,
  },
];
