const musicsSampledIn = [
  {
    song: "Edwin Birdsong - Cola Bottle Baby",
    title: "Cola Bottle Baby",
    genre: "Soul / Funk / Disco",
    url: "https://www.youtube.com/embed/fiD39jo5Yo4",
    sample: "sample appears at 0:00 and 4:51",
    hasBeenPlayed: false,
    sampleIn: "Harder, Better, Faster, Stronger",
  },
  {
    song: "Golden Sounds - Zamina Mina (Zangalewa)",
    title: "Zamina Mina (Zangalewa)",
    genre: "world",
    url: "https://www.youtube.com/embed/EpHQAw6eCOY",
    sample: "sampole appears at 0:10 and 7:30",
    hasBeenPlayed: false,
    sampleIn: "Waka Waka (This Time for Africa)",
  },
  {
    song: "Charles Aznavour - Parce Que Tu Crois",
    title: "Parce Que Tu Crois",
    genre: "Rock / Pop",
    url: "https://www.youtube.com/embed/28nMw4zmdKE?",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "What's the difference",
  },
  {
    song: "Chaka Khan - Fate",
    title: "Fate",
    genre: "Soul / Funk / Disco",
    url: "https://www.youtube.com/embed/S0NbcNc3HOk?",
    sample: "sample appears at 0:03",
    hasBeenPlayed: false,
    sampleIn: "Music Sounds Better With You",
  },
  {
    song: "The Clash - Straight to Hell",
    title: "Straight to Hell",
    genre: "Rock / Pop",
    url: "https://www.youtube.com/embed/t7SvtikTkrM",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "Paper Planes",
  },
  {
    song: "Patrice Rushen - Forget Me Nots",
    title: "Forget Me Nots",
    genre: "Soul / Funk / Disco",
    url: "https://www.youtube.com/embed/jtMHsNhQBvI?",
    sample: "sample appears at 0:04",
    hasBeenPlayed: false,
    sampleIn: "Men in Black",
  },
  {
    song: "The Andrew Oldham Orchestra - The Last TIme",
    title: "The Last TIme",
    url: "https://www.youtube.com/embed/9YrllfAMwHI",
    sample: "Sample appears at 0:17 and 1:37",
    hasBeenPlayed: false,
    sampleIn: "Bitter Sweet Symphony",
  },
  {
    song: "War - Smile Happy",
    title: "Smile Happy",
    url: "https://www.youtube.com/embed/s7vZSw7u0Js",
    sample: "sample appears at 0:16 ",
    hasBeenPlayed: false,
    sampleIn: "It Wasn't me",
  },
  {
    song: "Chi-Lites - Are You My Woman? (Tell Me So)",
    title: "Are You My Woman? (Tell Me So)",
    url: "https://www.youtube.com/embed/hm2YjDENPPU",
    sample: "sample appears at 0:09",
    hasBeenPlayed: false,
    sampleIn: "Crazy in Love",
  },
  {
    song: "Denny Jaeger - Untitled ",
    title: "Untitled",
    url: "https://www.youtube.com/embed/UaiBhPWWvKs?start=209",
    sample: "sample appears at 3:30",
    hasBeenPlayed: false,
    sampleIn: "Beat It",
  },
  {
    song: "Lata Mangeshkar and S. P. Balasubrahlanyam - Tere Mere Beech Mein ",
    title: "Tere Mere Beech Mein",
    url: "https://www.youtube.com/embed/IXVOKep5zeU",
    sample: "sample appears at 0:26 and 0:06",
    hasBeenPlayed: false,
    sampleIn: "Toxic",
  },
  {
    song: "Charles Aznavour - Parce Que Tu Crois",
    title: "Parce Que Tu Crois",
    url: "https://www.youtube.com/embed/28nMw4zmdKE",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "What's the difference",
  },
  {
    song: "Mike Brant - Mais Dans La Lumière",
    title: "Mais Dans La Lumière",
    url: "https://www.youtube.com/embed/GvN-ZTJG2L0",
    sample: "Sample appears at 0:01",
    hasBeenPlayed: false,
    sampleIn: "Crack a Bottle",
  },
  {
    song: "David McCallum - The Edge",
    title: "The Edge",
    url: " https://www.youtube.com/embed/6pG_3jZxzlo",
    sample: "Sample appears at 0:00, 0:10 and 0:05",
    hasBeenPlayed: false,
    sampleIn: "The Next Episode",
  },
  {
    song: "Labi Siffre - I Got The...",
    title: "I Got The...",
    url: "https://www.youtube.com/embed/xKISdd2mKzU?start=129",
    sample: "Sample appears at 2:10 and 2:31",
    hasBeenPlayed: false,
    sampleIn: "My Name Is",
  },
  {
    song: "Mtume - Juicy Fruit",
    title: "Juicy Fruit",
    url: "https://www.youtube.com/embed/9acYQyxL2qw?start=121",
    sample: "sample appears at 2:03",
    hasBeenPlayed: false,
    sampleIn: "Juicy",
  },
  {
    song: "Steve Winwood - Valerie",
    title: "Valerie",
    url: "https://www.youtube.com/embed/cbKNICg-REA?start=60",
    sample: "sample appears at 1:07 and 1:16",
    hasBeenPlayed: false,
    sampleIn: "Call on Me",
  },
  {
    song: "The Isley Brothers - Footsteps in the Dark",
    title: "Footsteps in the Dark",
    url: "https://www.youtube.com/embed/WRWtvbyprgo",
    sample: "sample appears at 0:06 and 0:42",
    hasBeenPlayed: false,
    sampleIn: "It Was a Good Day",
  },
  {
    song: "Chic - Soup for One",
    title: "Soup for One",
    url: "https://www.youtube.com/embed/f5-9N0DEfmM",
    sample: "sample appears at 0:06 ",
    hasBeenPlayed: false,
    sampleIn: "Lady (Hear Me Tonight)",
  },
  {
    song: "ABBA - Gimme! Gimme! Gimme! (A Man After Midnight)",
    title: "Gimme! Gimme! Gimme! (A Man After Midnight)",
    url: "https://www.youtube.com/embed/XEjLoHdbVeE?start=17",
    sample: "sample appears at 0:19 ",
    hasBeenPlayed: false,
    sampleIn: "Hung Up",
  },
  {
    song: "Timmy Thomas - Why Can't We Live Together",
    title: "Why Can't We Live Together",
    url: "https://www.youtube.com/embed/cFU-FJzPE80",
    sample: "sample appears at 0:00 and 0:12",
    hasBeenPlayed: false,
    sampleIn: "Hotline Bling",
  },
  {
    song: "Luiz Bonfa - Seville",
    title: "Seville",
    url: "https://www.youtube.com/embed/MSDl8w3wR2E",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "Somebody That I used to Know",
  },
  {
    song: "Jerry Rivera - Amores Como El Nuestro",
    title: "Amores Como El Nuestro",
    url: "https://www.youtube.com/embed/M85l1qW8x18",
    sample: "sample appears at 0:00",
    hasBeenPlayed: false,
    sampleIn: "Hips Don't Lie",
  },
  {
    song: "James Gang - Ashes, the Rain and I",
    title: "Ashes, the Rain and I",
    url: "https://www.youtube.com/embed/E-s738XHV6Q?start=210",
    sample: "sample appears at 3:33 and 4:09",
    hasBeenPlayed: false,
    sampleIn: "Right Here, Right Now",
  },
  {
    song: "Pierre Henry and Michel Colombier - Psyché Rock",
    title: "Psyché Rock",
    url: "https://www.youtube.com/embed/bcbrVLuWHRo",
    sample: "sample appears at 0:07 and 0:24",
    hasBeenPlayed: false,
    sampleIn: "Futurama Theme",
  },
  {
    song: "George Duke - I Love You More",
    title: "I Love You More",
    url: "https://www.youtube.com/embed/IEibygqqLZc",
    sample: "sample appears at 0:04 and 0:00",
    hasBeenPlayed: false,
    sampleIn: "Digital Love",
  },
];
